files:
  include: '**/*.s+(a|c)ss'
options:
  formatter: stylish
  merge-default-rules: true
rules:
  bem-depth: 1
  class-name-format:
    - 1
    - convention: hyphenatedbem
  extends-before-declarations: 0
  extends-before-mixins: 0
  force-attribute-nesting: 0
  force-element-nesting: 0
  leading-zero: 0
  mixin-name-format: 1
  mixins-before-declarations:
    - 1
    - exclude:
      - breakpoint
      - media
      - hocus
  no-ids: 1
  no-extends: 1
  no-qualifying-elements:
    - 1
    - allow-element-with-attribute: true
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order:
    - 1
    - order: 'smacss'
  quotes:
    - 1
    - style: double
  variable-name-format: 1
